### PR TITLE
Audience Targeting Tutorials 6.2

### PR DESCRIPTION
**Pull request by codyhoag**
These are the 6.2 Audience Targeting tutorials that need updating/converting to Liferay 7.0. Thanks! :smiley:

### CODE REVIEW

**Comment by juliocamarero** [comment]
@epgarcia we should update these tutorials as soon as the blade templates are merged.

**Comment by juliocamarero** [comment]
The Rules tutorial can be updated now :)

**Comment by epgarcia** [comment]
:thumbsup:

**Comment by juliocamarero** [comment]
https://github.com/codyhoag/liferay-docs/pull/91

**Pull request closed without merging**
